version: "3"
services:
  mlservice_blue:
    build: .
    environment:
      - MODEL_VERSION=v1.0.0
    ports:
      - "8080:8080"

  mlservice_green:
    build: .
    environment:
      - MODEL_VERSION=v1.1.0
    ports:
      - "8081:8080"

  nginx:
    image: nginx:latest
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlservice_blue
      - mlservice_green
